using Microsoft.EntityFrameworkCore;

namespace Models
{
    /// <summary>
    /// generated by
    /// Scaffold-DbContext -context MyDbContext -connection "Data Source=ENTWICKLUNG8\SQLEXPRESS;Initial Catalog=tdd-demo;Integrated Security=True;" -provider "Microsoft.EntityFrameworkCore.SqlServer"
    /// on Package Manager Console (default project "Models")
    /// </summary>
    public class MyDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        private const string ConnectionString =
            "Data Source=ENTWICKLUNG8\\SQLEXPRESS;Initial Catalog=tdd-demo;Integrated Security=True;"; // TODO from config file

        public MyDbContext()
        {
        }

        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer(ConnectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new UserEntityConfig());
        }
    }
}