using Microsoft.EntityFrameworkCore;

namespace Models
{
    /// <summary>
    /// generated by
    /// Scaffold-DbContext -context MyDbContext -connection "Data Source=ENTWICKLUNG8\SQLEXPRESS;Initial Catalog=tdd-demo;Integrated Security=True;" -provider "Microsoft.EntityFrameworkCore.SqlServer"
    /// on Package Manager Console (default project "Models")
    /// </summary>
    public class MyDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }

        public MyDbContext()
        {
        }

        public MyDbContext(DbContextOptions<MyDbContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer(
                    "Data Source=ENTWICKLUNG8\\SQLEXPRESS;Initial Catalog=tdd-demo;Integrated Security=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>()
                .Property(x => x.Name)
                .IsRequired()
                ;
            modelBuilder.Entity<User>()
                .Property(x => x.Email)
                .IsRequired()
                ;
        }
    }
}